"""Build sheet in assembly order, in markdown: what to buy, a miter-saw cut
list, then the build stage by stage (back frame on the wall first), every
mark a tape reading and every screw counted, each stage with its render.
Nothing here holds a number; it all comes from params.derive.

    .venv/bin/python projects/tote_bench/build_sheet.py     # -> projects/tote_bench/build/<version>.md
"""
from __future__ import annotations

from collections import Counter

from cacad.lumber import frac_in
from projects.tote_bench.params import ACTIVE_VERSIONS, IN, LUMBER, derive

ROLE = {"SILL": "sill", "LEDGER": "top ledger", "LEG-FRONT": "front leg blank", "LEG-BACK": "back leg", "RAIL": "rail",
        "SLAT": "shelf slat", "FOOTREST": "footrest", "PLANK": "top plank"}

# Assembly stages: (key, title, board-name fragments added at this stage). freecad_view renders each stage from this.
STAGES = [
    ("1_back_frame", "Back frame on the wall", ("SILL", "LEDGER", "-LEG-BACK")),
    ("2_rails", "Rails on the back legs", ("-RAIL-",)),
    ("3_front_legs", "Front legs, cut in place", ("-LEG-FRONT",)),
    ("4_shelf_footrest", "Shelf slats and footrest", ("-SLAT-", "-FOOTREST")),
    ("5_top", "Top planks", ("PLANK-",)),
]


def role(name: str) -> str:
    return next(v for k, v in ROLE.items() if k in name)


def stage_of(name: str) -> int:
    return next(i for i, (_, _, frag) in enumerate(STAGES) if any(p in name for p in frag))


def fi(x: float) -> str:
    return f"{frac_in(x)} in"


def count(d: dict, pred) -> int:
    return sum(1 for s in d["screws"] if pred(s))


def sheet(version: str) -> str:
    d = derive(version)
    t, ln, ws = d["t"], d["screw_len"], d["wall_screw"]
    rr, lr, sr = d["rail_rows"], d["lap_rows"], d["stud_rows"]
    cols = " | ".join("tote" if c["kind"] == "T" else "knee" for c in d["columns"])
    n_t = sum(1 for c in d["columns"] if c["kind"] == "T")
    img = lambda key: f"![{key}](../../../docs/img/tote_bench_{version}_{key}.png)"
    out = [f"# Tote bench `{version}`: build sheet", "",
           f"{d['note'][0].upper() + d['note'][1:]}. Top {fi(d['W'])} long x {fi(d['D'])} deep, {fi(d['H'])} high. "
           f"Columns, left to right: {cols}. Generated by `build_sheet.py` from `params.py`; change params, not this file.", "",
           "The order matters. The back frame goes on the wall first and becomes the level line. Everything after it",
           "hangs from it, and the front legs are cut to fit at the end, so the uneven floor never needs measuring.", ""]

    # --- buy ---
    out += ["## Buy", ""]
    for key, (stock, plan) in d["cut_plans"].items():
        lab = LUMBER[key.split()[0]]["label"]
        what = {"x2x4 120": "sill and top ledger, used whole. Make the sill pressure-treated: it sits on concrete",
                "x2x6 120": "top planks, used whole", "x2x4 96": "legs, rails, footrest", "x2x6 96": "shelf slats"}[key]
        out.append(f"- {len(plan)} x {lab}, {stock / IN / 12:g} ft: {what}. Sight down each board and pick straight ones.")
    out += [f"- {d['screw_spec']['label']}, {fi(ln)}: the bench takes {len(d['screws'])}; buy {-(-len(d['screws']) * 11 // 10)} or more",
            f"- {ws['label']}, {fi(ws['length'])}, for the wall: 2 per stud through each of the sill and the ledger, "
            f"about {d['wall_screws_nominal']} at 16 in stud spacing",
            "- A few composite shims, for leveling the sill on the lip",
            f"- {2 * n_t} x {d['tote_label'].split(',')[0]}", "",
            "Tools: a miter saw that crosscuts a 2x6 (5-1/2 in) square, drill/driver, stud finder, 4 ft level, tape, square, "
            "two clamps.", ""]

    # --- cut ---
    out += ["## Cut", "",
            "Every cut is square across the board. Clamp a stop block to the saw fence at each length and cut all of that",
            "length before moving the block. The sill, the ledger and the planks are whole 10 ft boards and get no cuts.", "",
            "| set stop at | cut | from | for |", "|---|---|---|---|"]
    cuts = Counter()
    for key, (stock, plan) in d["cut_plans"].items():
        if stock == 96 * IN:
            for st in plan:
                for nm, L in st:
                    cuts[(round(L, 6), LUMBER[key.split()[0]]["label"], role(nm))] += 1
    for (L, lab, r), n in sorted(cuts.items(), key=lambda kv: -kv[0][0]):
        out.append(f"| {fi(L)} | {n} | {lab} | {r}" + (" (trimmed in stage 3)" if "blank" in r else "") + " |")
    out += ["", "Stick by stick (1/8 in kerf allowed per cut):", ""]
    for key, (stock, plan) in d["cut_plans"].items():
        if stock != 96 * IN:
            continue
        lab = LUMBER[key.split()[0]]["label"]
        for i, st in enumerate(plan, start=1):
            used = sum(l + d["kerf"] for _, l in st)
            out.append(f"- {lab} #{i}: " + ", ".join(f"{fi(l)} {role(nm)}" for nm, l in st) + f"; offcut {fi(stock - used)}")
    out += ["", "Drill a pilot hole for every screw within 2 in of a board's end, so the pine does not split.", ""]

    # --- stages ---
    lap = count(d, lambda s: s[1].endswith("LEG-BACK"))
    marks = ", ".join(fi(x) for x in d["ladder_marks"])
    out += [f"## Stage 1: {STAGES[0][1]}", "", img(STAGES[0][0]), "",
            "1. Find the studs with a stud finder and mark each one on the wall, above bench height and just above the lip.",
            "2. Lay the sill and the ledger on the floor on their wide faces, parallel, the same edge toward you. "
            f"Space them so their far edges are {fi(d['ledger_z'][1] - d['sill_z'][0])} apart (the frame's full height).",
            f"3. Mark the back legs' left edges on both boards, from the left end: {marks}.",
            f"4. Lay a back leg ({fi(d['boards']['L0-LEG-BACK'][1][2])}) across both boards at each mark, its ends flush with the "
            "boards' far edges. Square it to the boards.",
            f"5. Screw each leg to each board with 2 screws on the leg's centre line, at {fi(lr[0])} and {fi(lr[1])} from the "
            f"board's far edge: {lap} in all.",
            "6. Stand the frame up on the lip, legs facing the room and the sill tight to the drywall. Put a level on the "
            "ledger and shim under the sill until it reads level along its length.",
            f"7. Drive 2 wall screws through the sill and 2 through the ledger at every stud, at {fi(sr[0])} and {fi(sr[1])} "
            "below each board's top edge. Those rows never meet the leg screws, wherever a stud falls.", ""]
    rails = count(d, lambda s: "-RAIL-" in s[1] and s[2].endswith("LEG-BACK"))
    out += [f"## Stage 2: {STAGES[1][1]}", "", img(STAGES[1][0]), "",
            f"Each back leg takes four {fi(d['rail_len'])} rails: a top pair and a mid pair, one on each face.", "",
            "1. Top rails: top edge flush with the leg top, back end tight against the ledger.",
            f"2. Mid rails: top edge {fi(d['mid_rail_from_top'])} below the leg top, back end flush with the leg's back face.",
            f"3. 2 screws through each rail into the leg, at {fi(rr[0])} and {fi(rr[1])} below the rail's top edge, centred on "
            f"the leg: {rails} in all.",
            "4. The rails stick out into the room. Prop each pair's front end on a scrap, or have a helper hold it, until "
            "stage 3.", ""]
    front = count(d, lambda s: "-RAIL-" in s[1] and s[2].endswith("LEG-FRONT"))
    out += [f"## Stage 3: {STAGES[2][1]}", "", img(STAGES[2][0]), "",
            "For each rail pair, one at a time:", "",
            "1. Put a level on the top rail, front to back, and set the front end level. Clamp the rails to a front leg "
            "blank stood between them on the floor, flush with the rails' front ends.",
            "2. Mark the top rail's top edge on the blank. Unclamp it, cut on the mark, and put it back on the floor between "
            "the rails.",
            f"3. Re-check level, then 2 screws through each rail into the leg, at {fi(rr[0])} and {fi(rr[1])} below the rail's "
            f"top edge: 8 per leg, {front} in all.",
            f"On a level floor the legs come out about {fi(d['front_leg_nominal'])}. Each one takes up whatever the floor and "
            "the lip do at that spot.", ""]
    slats = count(d, lambda s: "-SLAT-" in s[1])
    foot = count(d, lambda s: s[1].endswith("FOOTREST"))
    k = [c for c in d["columns"] if c["kind"] == "K"]
    out += [f"## Stage 4: {STAGES[3][1]}", "", img(STAGES[3][0]), "",
            f"1. In each tote column, lay {d['n_slats']} slats flat across the mid rails. The ends butt against the legs. "
            f"Put the back slat flush with the back legs' back faces and the front slat flush with the front legs. "
            f"Space the rest evenly ({fi(d['slat_gap'])} gaps).",
            f"2. 2 screws down through each slat into each rail, centred on the rail: {slats} in all."]
    if k:
        fr = d["boards"][f"C{k[0]['j']}-FOOTREST"]
        out += [f"3. Footrest ({fi(fr[1][0])}): on edge across the front faces of the two front legs either side of the "
                f"knee space, ends flush with the legs' far edges, top edge {fi(d['footrest_top'])} off the floor. "
                f"2 screws into each leg at {fi(rr[0])} and {fi(rr[1])} below its top edge: {foot} in all."]
    planks = count(d, lambda s: s[1].startswith("PLANK"))
    out += ["", f"## Stage 5: {STAGES[4][1]}", "", img(STAGES[4][0]), "",
            f"1. Lay the {d['top_planks']} planks across the ledger, the leg tops and the top rails. The back plank goes "
            f"{fi(d['wall_gap'])} off the drywall, the rest tight to it, ends flush with the frame's ends. The front plank "
            f"overhangs the front legs by {fi(d['top_overhang_front'])}.",
            f"2. 2 screws down through each plank into every top rail it crosses, centred on the rail: {planks} in all.", "",
            "## Totes", "", img("6_totes"), "",
            "Lower totes: handle out, slide in on the slab until the back touches the lip. Upper totes: slide in on the slats "
            f"until the back touches the ledger, which catches it by {fi(d['stop_engage'])}.", "",
            "## Check", "",
            f"- Lower tote lid to the slats: {fi(d['gap_over_lower'])}, and at least {fi(d['gap_over_lower_worst'])} even with "
            f"the lip {fi(d['lip_h_dev'])} low and the slab {fi(d['floor_dev'])} high under the tote.",
            f"- Upper tote lid to the planks: {fi(d['gap_over_upper'])}.",
            f"- Wall screws bite {fi(d['wall_bite'])} into the studs through {fi(d['drywall_t_max'])} drywall. That's more "
            "than the 6-diameter minimum.",
            f"- Every one of the {len(d['screws'])} wood screws is checked in the model: it passes {fi(t)} through its "
            f"board, bites {fi(ln - t)} into the next, and meets no other screw.", "",
            "Not measured, so the build allows for each: " + "; ".join(d["unverified"]) + "."]
    return "\n".join(out) + "\n"


def path(version: str) -> str:
    return __file__.rsplit("/", 1)[0] + f"/build/{version}.md"


if __name__ == "__main__":
    from pathlib import Path   # not a part file: the MCP sandbox rule (F23) is for part files
    build = Path(path(ACTIVE_VERSIONS[0])).parent
    build.mkdir(exist_ok=True)
    for old in build.glob("*.md"):
        if old.stem not in ACTIVE_VERSIONS:
            old.unlink()
    for v in ACTIVE_VERSIONS:
        Path(path(v)).write_text(sheet(v))
        print(f"{v}: {path(v)}")
