"""Build sheet per version, in markdown: what to buy, a miter-saw cut list
(stop-block table and stick-by-stick plan), and the assembly in order with
every mark as a tape reading and every screw counted. Nothing here holds a
number; it all comes from params.derive.

    .venv/bin/python projects/tote_bench/build_sheet.py     # -> projects/tote_bench/build/<version>.md
"""
from __future__ import annotations

from collections import Counter

from cacad.lumber import frac_in
from projects.tote_bench.params import ACTIVE_VERSIONS, IN, LUMBER, derive

ROLE = {"LEG-FRONT": "front leg", "LEG-BACK": "back leg", "RAIL": "rail", "SLAT": "shelf slat", "STOP": "upper tote stop",
        "FOOTREST": "footrest", "PLANK": "top plank"}


def role(name: str) -> str:
    for k, v in ROLE.items():
        if k in name:
            return v
    raise KeyError(name)


def fi(x: float) -> str:
    return f"{frac_in(x)} in"


def count(d: dict, pred) -> int:
    return sum(1 for s in d["screws"] if pred(s))


def sheet(version: str) -> str:
    d = derive(version)
    t, ln = d["t"], d["screw_len"]
    rows = d["screw_rows"]
    cols = " | ".join("tote" if c["kind"] == "T" else "knee" for c in d["columns"])
    n_l, n_t = d["n_ladders"], sum(1 for c in d["columns"] if c["kind"] == "T")
    knee = [c for c in d["columns"] if c["kind"] == "K"]
    out = [f"# Tote bench `{version}`: build sheet", "",
           f"{d['note'][0].upper() + d['note'][1:]}. Top {fi(d['W'])} long x {fi(d['D'])} deep, {fi(d['H'])} high. "
           f"Columns, left to right: {cols}. Generated by `build_sheet.py` from `params.py`; change params, not this file.", ""]

    # --- buy ---
    out += ["## Buy", ""]
    for kind, (stock, plan) in d["cut_plans"].items():
        if plan:
            lab = LUMBER[kind[:4]]["label"]
            extra = " (the top planks, used uncut)" if kind.endswith("planks") and not d["plank_cut"] else ""
            out.append(f"- {len(plan)} x {lab}, {stock / IN / 12:g} ft{extra}. Pick straight boards: sight down each one.")
    out += [f"- {d['screw_spec']['label']}, {fi(ln)}, one size for every joint: the bench takes {len(d['screws'])}; "
            f"buy at least {-(-len(d['screws']) * 11 // 10)}",
            f"- {2 * n_l} x {d['foot']['label']}: any 3/8-16 stud leveler with at least 1 in of travel and a pad no wider than 1-1/2 in",
            f"- {2 * n_t} x {d['tote_label'].split(',')[0]}", "",
            "Tools: a miter saw that crosscuts a 2x6 (5-1/2 in wide) square, drill/driver, tape, square, pencil, level.", ""]

    # --- cut ---
    out += ["## Cut", "",
            "Every cut is square across the board. Clamp a stop block to the saw fence at each length and cut all of that",
            "length before moving the block: the pieces come out identical, which is what makes the ladders identical.", "",
            "| set stop at | cut | from | for |", "|---|---|---|---|"]
    cuts = Counter()
    for nm, (kind, size, _) in d["boards"].items():
        if nm.startswith("PLANK") and not d["plank_cut"]:
            continue
        cuts[(round(max(size), 6), LUMBER[kind]["label"], role(nm))] += 1
    for (L, lab, r), n in sorted(cuts.items(), key=lambda kv: -kv[0][0]):
        out.append(f"| {fi(L)} | {n} | {lab} | {r} |")
    if not d["plank_cut"]:
        out.append(f"| (no cut) | {d['top_planks']} | 2x6 {d['plank_stock'] / IN / 12:g} ft | top plank, full length |")
    out += ["", "Stick by stick (1/8 in kerf allowed per cut):", ""]
    for kind, (stock, plan) in d["cut_plans"].items():
        lab = LUMBER[kind[:4]]["label"]
        for i, st in enumerate(plan, start=1):
            if kind.endswith("planks") and not d["plank_cut"]:
                continue
            used = sum(l + d["kerf"] for _, l in st)
            out.append(f"- {lab} {stock / IN / 12:g} ft #{i}: " + ", ".join(f"{fi(l)} {role(nm)}" for nm, l in st)
                       + f"; offcut {fi(stock - used)}")
    out.append("")

    # --- assemble ---
    rail_screws = count(d, lambda s: "-RAIL-" in s[1])
    per_ladder = rail_screws // n_l
    slat_screws = count(d, lambda s: "-SLAT-" in s[1])
    plank_screws = count(d, lambda s: s[1].startswith("PLANK"))
    stop_screws = count(d, lambda s: s[1].endswith("-STOP"))
    foot_screws = count(d, lambda s: s[1].endswith("-FOOTREST"))
    stops_each = stop_screws // n_t if n_t else 0
    out += ["## Assemble", "",
            "Drill a pilot hole for every screw within 2 in of a board's end, so the pine does not split.", "",
            f"**1. Feet.** In the bottom end of every leg ({2 * n_l} legs), centred, drill for the tee nut and tap it in.",
            "Use the hole size on the tee nut's packet. Thread a leveling foot in about halfway.", "",
            f"**2. Ladders ({n_l}, all identical).** Each is one front leg, one back leg and four rails.",
            "",
            f"- Lay a front leg ({fi(d['boards']['L0-LEG-FRONT'][1][2])}) and a back leg ({fi(d['boards']['L0-LEG-BACK'][1][2])}) "
            "on the floor on edge, a 1-1/2 in face up, parallel, with their tops lined up against a straight edge.",
            f"- Lay a top rail across them, on edge. Its top edge is flush with the leg tops, and its ends are flush with the legs' "
            f"outside edges, so the legs are {fi(d['rail_len'])} apart outside to outside.",
            f"- On both legs, mark {fi(d['mid_rail_from_top'])} down from the top. Lay a mid rail with its top edge on the marks, "
            "ends flush the same way.",
            f"- Screw each rail to each leg with 2 screws through the rail: at {fi(rows[0])} and {fi(rows[1])} below the rail's "
            f"top edge, centred on the leg's 1-1/2 in face. The screw runs into the leg's 3-1/2 in width. 8 screws per side.",
            "- Check the ladder is square (equal diagonals), flip it, and fasten the other two rails to the other face the same way.",
            f"- {per_ladder} screws per ladder, {rail_screws} in all. The back leg ends {fi(d['lip_h'])} short of the front leg: "
            "that is the lip.", "",
            "**3. Stand the ladders** against the wall, front legs on the floor and back legs on the lip, "
            f"the back legs {fi(d['wall_gap'])} off the wall.", ""]
    s = 4
    if n_t:
        out += [f"**{s}. Shelf slats (spacers too).** In each tote column, lay {d['n_slats']} slats flat across the two mid rails. "
                "The slat ends butt against the leg faces on both sides, so the slats set the column width "
                f"({fi(d['tote_col'])} between rail faces).",
                f"- Back slat's back edge flush with the back legs' back faces, front slat's front edge flush with the front legs' "
                f"front faces, the rest evenly spaced "
                f"({fi(d['slat_gap'])} gaps).",
                f"- 2 screws down through the slat into each rail it crosses, centred on the rail: {slat_screws} in all.", ""]
        s += 1
    if knee:
        k = knee[0]
        fr = d["boards"][f"C{k['j']}-FOOTREST"]
        out += [f"**{s}. Footrest.** Set the knee-space ladders {fi(d['knee'])} apart between rail faces. Screw the "
                f"{fi(fr[1][0])} footrest on edge across the front faces of the two front legs. Its ends are flush with the legs' "
                f"far edges. Its top edge is {fi(d['footrest_top'] - d['foot_h'])} above the leg bottoms, "
                f"{fi(d['footrest_top'])} off the floor with the feet at mid-travel.",
                f"- 2 screws into each leg at {fi(rows[0])} and {fi(rows[1])} below its top edge: {foot_screws} in all.", ""]
        s += 1
    over = d["top_overhang_end"]
    out += [f"**{s}. Top.** Lay the {d['top_planks']} planks across all the top rails. The back plank is {fi(d['wall_gap'])} off "
            f"the wall, and the planks are tight to each other. They overhang the end rails by {fi(over)} and the front legs by "
            f"{fi(d['top_overhang_front'])}.",
            f"- 2 screws down through each plank into every top rail it crosses, centred on the rail: {plank_screws} in all. "
            "Check that the bench is square before the last ones go in.", ""]
    s += 1
    if n_t:
        out += [f"**{s}. Upper tote stops.** In each tote column, lay a stop (2x4, flat) on the back slat, back edges flush. "
                f"{stops_each} screws down into the slat: {stop_screws} in all.", ""]
        s += 1
    out += [f"**{s}. Level.** Turn the feet until the top is level both ways. Each foot moves about "
            f"{fi(d['foot_travel_each_way'])} either way from the start, enough for the slab and the lip.", "",
            f"**{s + 1}. Totes.** Slide each lower tote in, handle out, until it touches the lip. Slide each upper tote in "
            "until it touches the stop.", "",
            "Optional: once you know where the wall studs are, drive a couple of long screws through the back of the top "
            "rails into them. The bench can't go backward against the lip, and this keeps it from racking along the wall.", "",
            "## Check", "",
            f"Tote lid to slat underside {fi(d['gap_over_lower'])} with the slab {fi(d['floor_dev'])} high under it; "
            f"upper lid to planks {fi(d['gap_over_upper'])}. Screws: {len(d['screws'])}, every one checked in the model to "
            f"pass {fi(t)} through its board and bite {fi(ln - t)} into the next, and to meet no other screw.", "",
            "Not measured, so the design allows for each: " + "; ".join(d["unverified"]) + "."]
    return "\n".join(out) + "\n"


def path(version: str) -> str:
    return __file__.rsplit("/", 1)[0] + f"/build/{version}.md"


if __name__ == "__main__":
    from pathlib import Path   # build_sheet.py is not a part file; only part files keep the MCP sandbox rule (F23)
    for v in ACTIVE_VERSIONS:
        p = Path(path(v))
        p.parent.mkdir(exist_ok=True)
        p.write_text(sheet(v))
        print(f"{v}: {p}")
